# Express.js microservice with file uploads
app = "user-service"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3000"
  JWT_SECRET = "$JWT_SECRET"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 5

[[http_service.checks]]
  interval = "30s"
  timeout = "5s"
  grace_period = "10s"
  method = "GET"
  path = "/health"

[[vm]]
cpus = 1
cpu_kind = "shared"
memory_mb = 1024

[mounts]
source = "uploads"
destination = "/app/uploads"