# Rails API with PostgreSQL and Redis
app = "my-rails-api"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[env]
  DATABASE_URL = "postgresql://postgres:$DATABASE_PASSWORD@my-rails-api-db.internal:5432/production"
  REDIS_URL = "redis://my-rails-api-redis.internal:6379"
  RAILS_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 2
  max_machines_running = 10

[[vm]]
cpus = 2
cpu_kind = "shared"
memory_mb = 2048

[[vm]]
cpus = 1
cpu_kind = "shared"
memory_mb = 1024

[[mounts]]
source = "app_data"
destination = "/app/storage"

[[mounts]]
source = "log_data"
destination = "/app/log"